pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3"
        WEB_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/web"
        E2E_WEB_TESTING_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/e2e-web"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Audit') {
            steps {
                dir("${SCRIPTS_PATH}") {
                    sh('./audit.sh test')
                }
            }
        }
        stage('Build') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                    echo "Build web"
                    npm install
                    npm start &>/dev/null &
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${E2E_WEB_TESTING_PATH}") {
                   sh """
                    echo "Build Test"
                    npm install
                    echo "Run Test"
                    npm test
                    """
                }
            }
        }
        stage('Test Lighthouse DEV') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Lighthouse test"
                    sh lighthouse-testing.sh test
                    """
                }
            }
            post {
                always {
                    dir("${SCRIPTS_PATH}") {
                        sh """
                            sh lighthouse-testing.sh close
                            """
                    }
                    sh """
                        lsof -ti :3000 | xargs kill &
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}