pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3"
        WEB_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/web"
        E2E_WEB_TESTING_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/e2e-web"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                    echo "Build web"
                    npm install
                    npm start
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Test"
                    """
                }
            }
            post: {
                always: {
                    sh """
                        lsof -ti :3000 | xargs kill &
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}