pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
	stage('Exercise_1') {
		sh('../dojo-2/solutions/exercise_1_ronnapat.sh')
	}
	stage('Exercise_2') {
		sh('../dojo-2/solutions/exercise_2_ronnapat.sh')
	}
    }
}
